components:
  schemas:
    ApplyAttributes:
      additionalProperties: true
      properties:
        country:
          description: Country
          enum:
            - ES
            - IT
            - PT
            - FR
          type: string
        deliveryType:
          description: DeliveryType
          enum:
            - DIRECT
            - REVERSE
          type: string
        instructions:
          description: Instructions
          items:
            $ref: "#/components/schemas/Instruction"
          type: array
        operationalModel:
          description: Operational Model
          enum:
            - WAREHOUSE
            - STORE
          type: string
        serviceType:
          description: ServiceType
          type: string
      required:
        - operationalModel
        - serviceType
        - deliveryType
        - country
        - instructions
      type: object
    ApplyRetailerConfigurationReqBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: http://localhost:8080/schemas/ApplyRetailerConfigurationReqBody.json
          format: uri
          readOnly: true
          type: string
        data:
          items:
            $ref: "#/components/schemas/Data"
          type: array
      required:
        - data
      type: object
    Data:
      additionalProperties: false
      properties:
        attributes:
          $ref: "#/components/schemas/ApplyAttributes"
        type:
          default: configurations
          type: string
      required:
        - type
        - attributes
      type: object
    ErrorEntity:
      additionalProperties: false
      properties:
        code:
          type: string
        detail:
          type: string
        id:
          type: string
        source:
          $ref: "#/components/schemas/Source"
        status:
          format: int64
          type: integer
        title:
          type: string
        value: {}
      required:
        - id
        - status
        - title
      type: object
    ErrorsRespo:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: http://localhost:8080/schemas/ErrorsRespo.json
          format: uri
          readOnly: true
          type: string
        data: {}
        errors:
          items:
            $ref: "#/components/schemas/ErrorEntity"
          type: array
      required:
        - data
        - errors
      type: object
    Instruction:
      additionalProperties: false
      properties:
        attempts:
          description: Attempts
          format: int32
          minimum: 0
          type: integer
        priority:
          description: Priority
          format: int32
          maximum: 20
          minimum: 0
          type: integer
        steps:
          description: Steps
          items:
            $ref: "#/components/schemas/Step"
          type: array
        type:
          description: Instruction Type
          enum:
            - PICKUP_WH
            - FAILED_PICKUP_WH
            - DELIVERY_CUSTOMER
            - DELIVERY_HOUSEHOLD
            - DELIVERY_3RD_PARTY
            - FAILED_DELIVERY_CUSTOMER
            - PICKUP_CUSTOMER
            - FAILED_PICKUP_CUSTOMER
            - FAILED_DELIVERY_WH
          type: string
      required:
        - type
        - steps
      type: object
    Source:
      additionalProperties: false
      properties:
        header:
          type: string
        parameter:
          type: string
        path:
          type: string
        pointer:
          type: string
      type: object
    Step:
      additionalProperties: false
      properties:
        name:
          description: Name of the step
          enum:
            - SCAN
            - COLLECT_BARCODES
            - PHOTO
            - ID_NUMBER
            - SIGNATURE
            - PASSCODE
            - OTP
            - MANUAL_CONFIRMATION
            - CONFIGURABLE_TEXT
          type: string
      required:
        - name
      type: object
  securitySchemes:
    bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: test@test.com
    name: test
    url: https://test.co/contact-us/
  description: API for synchronization REMS configurations and LMO
  license:
    name: internal
    url: https://test.co
  title: Configurations manager API
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/v3/configManager/retailers/{retailerId}/configurations:
    post:
      description: Apply up-to-date retailer configurations
      operationId: apply-retailer-configuration
      parameters:
        - in: path
          name: retailerId
          required: true
          schema:
            format: base64
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplyRetailerConfigurationReqBody"
        required: true
      responses:
        "204":
          description: No Content
          headers:
            Content-Type:
              schema:
                type: string
            Last-Modified:
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorsRespo"
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorsRespo"
          description: Unauthorized
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorsRespo"
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorsRespo"
          description: Internal Server Error
      security:
        - bearer: []
      summary: Apply up-to-date retailer configuration
      tags:
        - Configurations
servers:
  - description: Current configuration server URL
    url: http://localhost:8080
  - description: For local development
    url: http://localhost:8080
tags:
  - description: Managing retailer configurations
    name: Configurations
